package com.f1tracker.ui.theme

import androidx.compose.ui.graphics.Color

// F1 Brand Colors
val F1Red = Color(0xFFE10600)
val F1DarkRed = Color(0xFF9C0000)
val F1Black = Color(0xFF15151E)
val F1White = Color(0xFFFFFFFF)

// Material 3 Light Theme Colors
val md_theme_light_primary = Color(0xFFE10600)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDAD5)
val md_theme_light_onPrimaryContainer = Color(0xFF3E0001)
val md_theme_light_secondary = Color(0xFF775652)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDAD5)
val md_theme_light_onSecondaryContainer = Color(0xFF2C1512)
val md_theme_light_tertiary = Color(0xFF705C2E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFCDFA6)
val md_theme_light_onTertiaryContainer = Color(0xFF251A00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF201A19)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF201A19)
val md_theme_light_surfaceVariant = Color(0xFFF5DDDA)
val md_theme_light_onSurfaceVariant = Color(0xFF534341)
val md_theme_light_outline = Color(0xFF857370)
val md_theme_light_inverseOnSurface = Color(0xFFFBEEEC)
val md_theme_light_inverseSurface = Color(0xFF362F2E)
val md_theme_light_inversePrimary = Color(0xFFFFB4A8)

// Material 3 Dark Theme Colors
val md_theme_dark_primary = Color(0xFFFFB4A8)
val md_theme_dark_onPrimary = Color(0xFF640100)
val md_theme_dark_primaryContainer = Color(0xFF8E0000)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDAD5)
val md_theme_dark_secondary = Color(0xFFE7BDB8)
val md_theme_dark_onSecondary = Color(0xFF442926)
val md_theme_dark_secondaryContainer = Color(0xFF5D3F3B)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDAD5)
val md_theme_dark_tertiary = Color(0xFFDFC38C)
val md_theme_dark_onTertiary = Color(0xFF3E2E05)
val md_theme_dark_tertiaryContainer = Color(0xFF564419)
val md_theme_dark_onTertiaryContainer = Color(0xFFFCDFA6)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF201A19)
val md_theme_dark_onBackground = Color(0xFFEDE0DE)
val md_theme_dark_surface = Color(0xFF201A19)
val md_theme_dark_onSurface = Color(0xFFEDE0DE)
val md_theme_dark_surfaceVariant = Color(0xFF534341)
val md_theme_dark_onSurfaceVariant = Color(0xFFD8C2BF)
val md_theme_dark_outline = Color(0xFFA08C89)
val md_theme_dark_inverseOnSurface = Color(0xFF201A19)
val md_theme_dark_inverseSurface = Color(0xFFEDE0DE)
val md_theme_dark_inversePrimary = Color(0xFFBF0002)

// Team Colors
val RedBullRacing = Color(0xFF3671C6)
val Ferrari = Color(0xFFE8002D)
val Mercedes = Color(0xFF27F4D2)
val McLaren = Color(0xFFFF8000)
val AstonMartin = Color(0xFF229971)
val Alpine = Color(0xFFFF87BC)
val Williams = Color(0xFF64C4FF)
val AlphaTauri = Color(0xFF5E8FAA)
val AlfaRomeo = Color(0xFFC92D4B)
val Haas = Color(0xFFB6BABD)

